
-- 业务规则
DROP TABLE IF EXISTS rule_business;
CREATE TABLE rule_business
(
    id BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    rid BIGINT(20) NOT NULL COMMENT '外键ID',
    business_name VARCHAR(30) NULL DEFAULT NULL COMMENT '业务规则名',
    business VARCHAR(30) NULL DEFAULT NULL COMMENT '业务',
    rule_group VARCHAR(20) NULL DEFAULT NULL COMMENT '规则组',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期',
    update_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日期',
    PRIMARY KEY (id) COMMENT '业务规则表'
);
-- 外键
-- ALTER TABLE rule_business ADD FOREIGN KEY (rid) REFERENCES rule(id);

-- 条件规则
DROP TABLE IF EXISTS rule;
CREATE TABLE rule
(
    id BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    rule_name VARCHAR(30) NULL DEFAULT NULL COMMENT '条件规则名',
    rule_group VARCHAR(20) NULL DEFAULT NULL COMMENT '条件规则组',
    expression VARCHAR(50) NULL DEFAULT NULL COMMENT '条件表达式',
    expression_language VARCHAR(50) NULL DEFAULT NULL COMMENT '表达式语言',
    is_common_rule TINYINT(1) NOT NULL DEFAULT 0 COMMENT '是否公共规则 0--普通规则, 1--公共规则',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期',
    update_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日期',
    PRIMARY KEY (id) COMMENT '条件规则表'
);

-- 规则因子
DROP TABLE IF EXISTS rule_factor;
CREATE TABLE rule_factor
(
    id BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    rid BIGINT(20) NOT NULL COMMENT '外键ID',
    factor_name VARCHAR(30) NULL DEFAULT NULL COMMENT '因子名称',
    factor VARCHAR(20) NULL DEFAULT NULL COMMENT '因子',
    factor_method VARCHAR(20) NULL DEFAULT NULL COMMENT '查询因子方法',
    create_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建日期',
    update_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日期',
    PRIMARY KEY (id) COMMENT '规则因子表'
);

-- 组合唯一索引
-- CREATE UNIQUE INDEX 索引名 ON rule_factor(eid, factor);

-- 组合约束
-- ALTER TABLE rule_factor ADD UNIQUE KEY(eid, factor);
