server:
  port: 8081
  servlet:
    context-path: /framework

spring:
  datasource:
    dynamic:
      primary: mysql_1 #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        mysql_1:  # 启动参数 ( idea 设置 Program arguments , 服务器可以设置为启动环境变量 ) --mpw.key=密钥
          url: mpw:rYx+0uytDh7CuBRwqKmepNgj8h8HwlUp14oUOncEJnrbpCB6a/R9t3Z7/fkIijr2NPf8o0nxV0qjAQKb+Km3wI5VbyBB7xKuChtM+5AaCjFxdkQUV0fesg5gbIa0iUnaez4MzSNx5dibBXHNvK9smBQ/LfW0cZ2258CzPxMmRkU=
          username: mpw:Fb5kA34qJaAkRm4rsA2rhQ==
          password: mpw:WnpNVn7/v7XPXIr/Cu4SlQ==
          driver-class-name: com.mysql.cj.jdbc.Driver
        mysql_2:
          url: mpw:rYx+0uytDh7CuBRwqKmepHPX31LfwSOOlaezO+r7/YIbwfxJ1FGktUJFiPxrWyHH5ur7MTxcIOeiqrJpXMZ5bzQ1AG6rgeICvmMQ/KLrBM26e4r3ufZqTHz6tKm3RZr4CGT0YHfp1RfAtBz+BcRNxpktuk52rr/RoHT6V00Teow=
          username: mpw:Fb5kA34qJaAkRm4rsA2rhQ==
          password: mpw:WnpNVn7/v7XPXIr/Cu4SlQ==
          driver-class-name: com.mysql.cj.jdbc.Driver

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    serialization:
      write-dates-as-timestamps: false
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
      # 开发时关闭缓存，页面实时刷新
    cache: false

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 1
      # 删除后
      logic-delete-value: 0
    banner: false #关闭控制台LOGO

# 开启
swagger:
  show: true


